name: Pipeline Integração Contínua Vercel

on:
    push:
        branches: [ main ]

    pull_request:
        branches: [ main ]

jobs:
    test-and-build:
        runs-on: ubuntu-latest

        steps:
            - name: Baixar código
              uses: actions/checkout@v4

            - name: Configurar Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'

            - name: Instalar dependências
              run: npm install

            - name: Instalar Vercel CLI
              run: npm install -g vercel

            - name: Realizar teste de build
              run: npm test

            - name: Deploy para Vercel
              run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
              env: 
                VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

            - name: Relatório Final
              if: always()
              run: |
                echo "========================================="
                echo "Status do Pipeline: ${{ job.status }}"
                echo "========================================="